# Generated by Django 5.2.8 on 2025-11-18 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='ドメイン')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='メディア名')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ジャンル名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to=settings.AUTH_USER_MODEL, verbose_name='オーナー')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='案件名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='tracking.genre', verbose_name='ジャンル')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='オーナー')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='キーワード')),
                ('search_volume', models.IntegerField(blank=True, null=True, verbose_name='月間検索ボリューム')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='tracking.project', verbose_name='案件')),
            ],
            options={
                'unique_together': {('project', 'text')},
            },
        ),
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_rank', models.IntegerField(default=50, verbose_name='最大抽出順位')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='実行日時')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tracking.project', verbose_name='案件')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='SEO順位')),
                ('page_url', models.URLField(max_length=2048, verbose_name='掲載記事リンク')),
                ('title', models.CharField(blank=True, max_length=512, verbose_name='記事タイトル')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tracking.keyword', verbose_name='キーワード')),
                ('media_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tracking.mediasite', verbose_name='メディアサイト')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tracking.extractionrun', verbose_name='実行履歴')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField(max_length=2048, verbose_name='アフィリエイトリンクURL')),
                ('asp_name', models.CharField(blank=True, max_length=100, verbose_name='ASP名')),
                ('product_name', models.CharField(blank=True, max_length=255, verbose_name='商品名')),
                ('search_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_links', to='tracking.searchresult', verbose_name='検索結果記事')),
            ],
        ),
    ]
