# Generated by Django 5.2.8 on 2025-12-03 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchresult',
            options={'ordering': ['rank']},
        ),
        migrations.AlterUniqueTogether(
            name='searchresult',
            unique_together={('run', 'keyword', 'rank')},
        ),
    ]
